### ISSUE TITLE
Stuck on holdings

### ISSUE THREAD

**Issue by mattfox27** [TCRAKN/ESP8266-Coingecko#1]
Hi,

I have been trying to get this to work however once it goes through everything it gets to the holdings and just stops

**Comment by TCRAKN** [comment]
Hi Matt,

The first thing I'd suggest you do is update the site fingerprint.  This is usually the problem.  However, it would normally stop at the time screen.

Other things to check:

a. Update all libraries and boards
b. Check the Serial Monitor.  You'll get more information here than you'll see on the OLED
c. Don't rely on the website I've included in the sketch.  It's best to get the site fingerprint from your browser on your PC/Mac.  Search for how to do this, as it's different for all browsers.

Hope this helps
Abdul-Khaliq

[https://email04.godaddy.com/download.php?key=606ccfbe846ba&inline=1&source=signature]<https://widget.worldcommunitygrid.org/discover.action?recruiterId=1134365>Help projects like: OpenPandemics - COVID-19, Africa Rainfall Project, Microbiome Immunity Project, Smash Childhood Cancer, Help Stop TB, Mapping Cancer Markers

Join World Community Grid today!<https://widget.worldcommunitygrid.org/discover.action?recruiterId=1134365>

________________________________
From: Matt Klimmer ***@***.***>
Sent: 29 April 2023 19:00
To: TCRAKN/ESP8266-Coingecko ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TCRAKN/ESP8266-Coingecko] Stuck on holdings (Issue #1)


Hi,

I have been trying to get this to work however once it goes through everything it gets to the holdings and just stops
