### ISSUE TITLE
only seeing hours 

### ISSUE THREAD

**Issue by lello98** [TCRAKN/ESP8266-Coingecko#3]
hi i don t know if is my fault but the screen displays only a hour and nothing different

thanks a lot

**Comment by lello98** [comment]
[![unnamed](https://github.com/TCRAKN/ESP8266-Coingecko/assets/30060000/78bd44b1-ec34-43d8-9db9-69c2bc13c17f)](warning: ISO C++ forbids converting a string constant to 'char*')

i think that the issue if you can help me

**Comment by TCRAKN** [comment]
Have you checked that the Fingerprint is up-to-date?  The current fingerprint is:
0F 5E D5 EA 64 AE 5D A4 B3 CE A3 16 DC 90 12 02 56 3B 90 B9

The warnings of "string constant to 'char*'" you can ignore.

**Comment by lello98** [comment]
you are the man can i ask you how to find fingerprint in future i used it but was different
https://www.grc.com/fingerprints.htm

**Comment by TCRAKN** [comment]
grc is usually out of date.  Go directly to your browser for the correct fingerprint.  Chrome instructions are in the code.

Abdul-Khaliq
44 (0)7976 55 33 05 (UK)
[https://email04.godaddy.com/download.php?key=606ccfbe846ba&inline=1&source=signature]<https://widget.worldcommunitygrid.org/discover.action?recruiterId=1134365>
Help projects like: OpenPandemics - COVID-19, Africa Rainfall Project, Microbiome Immunity Project, Smash Childhood Cancer, Help Stop TB, Mapping Cancer Markers

Join World Community Grid today!<https://widget.worldcommunitygrid.org/discover.action?recruiterId=1134365>

________________________________

**Comment by lello98** [comment]
thanks a lot

**Comment by TCRAKN** [comment]
Glad it worked out.

Abdul-Khaliq
44 (0)7976 55 33 05 (UK)
[https://email04.godaddy.com/download.php?key=606ccfbe846ba&inline=1&source=signature]<https://widget.worldcommunitygrid.org/discover.action?recruiterId=1134365>
Help projects like: OpenPandemics - COVID-19, Africa Rainfall Project, Microbiome Immunity Project, Smash Childhood Cancer, Help Stop TB, Mapping Cancer Markers

Join World Community Grid today!<https://widget.worldcommunitygrid.org/discover.action?recruiterId=1134365>

________________________________

**Comment by lello98** [comment]
i m just wondering why is saying £44140

**Comment by TCRAKN** [comment]
Around line 258, you need to edit for your own holdings.

It should display each holding and its value and cycle through.

It does lock up sometimes, for which I'm not yet sure.  A reset usually works.

**Comment by TCRAKN** [comment]
Checkout this on how it should function:

https://www.youtube.com/shorts/TRMqznXfxHI

**Comment by lello98** [comment]
hi i went to bed thank you very much i checked the video and in mine seems to block after 1 minutes in the last called livepeer. ps thank you so much

**Comment by lello98** [comment]
i m sorry you re very helpful to me but i dont understand how to reset time min line 258 if you are able to help me please thank you so much i tried to edit whithou any success

**Comment by lello98** [comment]
i m not good in coding i placed an ESP.restart(); thnak again

**Comment by TCRAKN** [comment]
Time is taken from an Internet time server.  so you need to add your timezone offset.  getting time happens between lines 134-147.

Check out the documentation for NTPClient.h to set timezone.

**Comment by TCRAKN** [comment]
https://github.com/arduino-libraries/NTPClient/blob/master/examples/Advanced/Advanced.ino

**Comment by lello98** [comment]
Yes i did that i mean i used ESP.restart() because it was stopping working after the last price . The time zone is now fine . It s such a beautiful tool
